### ISSUE TITLE
wallet testing 

### ISSUE THREAD

**Issue by Iceymann18777** [facundofarias/test-payments#5]
city culture erupt gym coast clean ranch memory wet penalty rose okay useless law walk aware weekend turkey enter loyal strike social blind during![PSX_20210728_202301.jpg](https://user-images.githubusercontent.com/82147328/127361983-a0fb258a-79d2-49b3-9794-4be6747ff9fe.jpg)

**Comment by lilmonero** [comment]
YAHOOO! c'mon n tell me a little mo
